<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_305620</name>
   <tag></tag>
   <elementGuidId>9d89e870-f007-4fce-889b-9628d5f53d0b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ReadingPaneContainerId']/div/div/div/div[2]/div/div/div/div/div/div/div/div[3]/div/div/div/div[2]/table/tbody/tr[4]/td/table/tbody/tr/td/table/tbody/tr/td/table/tbody/tr/td/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>4b686692-c93f-43f4-8469-848b183e4dad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>305620 </value>
      <webElementGuid>f6a49f5a-5c68-4698-aec5-e35a38d364e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ReadingPaneContainerId&quot;)/div[1]/div[@class=&quot;g_zET&quot;]/div[@class=&quot;MtujV&quot;]/div[@class=&quot;L72vd&quot;]/div[@class=&quot;Q8TCC yyYQP customScrollBar&quot;]/div[1]/div[@class=&quot;aVla3&quot;]/div[1]/div[1]/div[@class=&quot;wide-content-host&quot;]/div[@class=&quot;SlLx9 isFirstCard byzS1&quot;]/div[@class=&quot;XbIp4 jmmB7 GNqVo yxtKT allowTextSelection&quot;]/div[1]/div[@class=&quot;rps_3726&quot;]/div[1]/div[@class=&quot;R1UVb&quot;]/table[1]/tbody[1]/tr[4]/td[@class=&quot;x_no-padding-top-bottom-mobile&quot;]/table[@class=&quot;x_container&quot;]/tbody[1]/tr[1]/td[@class=&quot;x_container-padding&quot;]/table[@class=&quot;x_columns-container&quot;]/tbody[1]/tr[1]/td[@class=&quot;x_force-col&quot;]/table[@class=&quot;x_col-3&quot;]/tbody[1]/tr[1]/td[1]/div[2]</value>
      <webElementGuid>f2e66b6e-cb04-4bb4-a67c-8df4264463ce</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ReadingPaneContainerId']/div/div/div/div[2]/div/div/div/div/div/div/div/div[3]/div/div/div/div[2]/table/tbody/tr[4]/td/table/tbody/tr/td/table/tbody/tr/td/table/tbody/tr/td/div[2]</value>
      <webElementGuid>d8adb391-e448-4459-986f-ca2742eb1f63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hola, sjagtap'])[1]/following::div[2]</value>
      <webElementGuid>5bbe1ccd-b513-40f8-8d45-ee072e7d19d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Este es un procedimiento 100% seguro.'])[1]/preceding::div[1]</value>
      <webElementGuid>4f275a8d-35aa-4226-ae74-ec7654061457</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reply'])[2]/preceding::div[2]</value>
      <webElementGuid>dd018886-e095-41cc-9fcd-d01c27d3bb4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/div[2]</value>
      <webElementGuid>286b7605-3f86-4c1f-b20f-548a01b4ce5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '305620 ' or . = '305620 ')]</value>
      <webElementGuid>2365aae3-cdb1-40c3-8564-eb903d9b35a8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
