<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>strong_305620</name>
   <tag></tag>
   <elementGuidId>3ba704d3-0a62-4b83-8dd1-cfde1246e97b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ReadingPaneContainerId']/div/div/div/div[2]/div/div/div/div/div/div/div/div[3]/div/div/div/div[2]/table/tbody/tr[4]/td/table/tbody/tr/td/table/tbody/tr/td/table/tbody/tr/td/div[2]/strong</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>strong</value>
      <webElementGuid>ea7e67f8-1178-43bb-b1b6-9d5f489540c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>305620</value>
      <webElementGuid>fac0820c-60d8-4801-bb97-06fa093e3aa8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ReadingPaneContainerId&quot;)/div[1]/div[@class=&quot;g_zET&quot;]/div[@class=&quot;MtujV&quot;]/div[@class=&quot;L72vd&quot;]/div[@class=&quot;Q8TCC yyYQP customScrollBar&quot;]/div[1]/div[@class=&quot;aVla3&quot;]/div[1]/div[1]/div[@class=&quot;wide-content-host&quot;]/div[@class=&quot;SlLx9 isFirstCard byzS1&quot;]/div[@class=&quot;XbIp4 jmmB7 GNqVo yxtKT allowTextSelection&quot;]/div[1]/div[@class=&quot;rps_3726&quot;]/div[1]/div[@class=&quot;R1UVb&quot;]/table[1]/tbody[1]/tr[4]/td[@class=&quot;x_no-padding-top-bottom-mobile&quot;]/table[@class=&quot;x_container&quot;]/tbody[1]/tr[1]/td[@class=&quot;x_container-padding&quot;]/table[@class=&quot;x_columns-container&quot;]/tbody[1]/tr[1]/td[@class=&quot;x_force-col&quot;]/table[@class=&quot;x_col-3&quot;]/tbody[1]/tr[1]/td[1]/div[2]/strong[1]</value>
      <webElementGuid>4dc14678-c973-468e-a9ab-1c36be82cf78</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ReadingPaneContainerId']/div/div/div/div[2]/div/div/div/div/div/div/div/div[3]/div/div/div/div[2]/table/tbody/tr[4]/td/table/tbody/tr/td/table/tbody/tr/td/table/tbody/tr/td/div[2]/strong</value>
      <webElementGuid>130be4a4-17ab-4301-a71d-6b238f488fc3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hola, sjagtap'])[1]/following::strong[1]</value>
      <webElementGuid>15c978a6-2b25-4374-9135-820495ef0e0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Este es un procedimiento 100% seguro.'])[1]/preceding::strong[1]</value>
      <webElementGuid>de7bc4f7-5699-4379-8652-6c9120f6e5b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reply'])[2]/preceding::strong[2]</value>
      <webElementGuid>6f63144f-738e-4f11-9afe-6726a860045e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='305620']/parent::*</value>
      <webElementGuid>27322e43-8027-4ab2-bfb1-a0988830740e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/strong</value>
      <webElementGuid>1b71b075-8f2b-4d97-b3b7-2002c32c67f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//strong[(text() = '305620' or . = '305620')]</value>
      <webElementGuid>29d9319b-10dd-4dfa-bfca-431bb7e19a47</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
