<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>strong_559036</name>
   <tag></tag>
   <elementGuidId>bee05b08-bfc7-4b97-90fb-173afe008587</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//div[@style='background:#efefef; border:1px solid #efefef; color:#E51E20; text-align:center; font-size:42px; padding:20px']//strong)</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>strong</value>
      <webElementGuid>b7e7b22d-6eca-487e-97ce-6acddfde2331</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>559036</value>
      <webElementGuid>eed9baeb-12fa-4b38-892a-f5eac5c50d0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ReadingPaneContainerId&quot;)/div[1]/div[@class=&quot;g_zET&quot;]/div[@class=&quot;MtujV&quot;]/div[@class=&quot;L72vd&quot;]/div[@class=&quot;Q8TCC yyYQP customScrollBar&quot;]/div[2]/div[@class=&quot;aVla3&quot;]/div[1]/div[1]/div[@class=&quot;wide-content-host&quot;]/div[@class=&quot;SlLx9 isFirstCard byzS1&quot;]/div[@class=&quot;XbIp4 jmmB7 GNqVo yxtKT allowTextSelection&quot;]/div[1]/div[@class=&quot;rps_7183&quot;]/div[1]/div[@class=&quot;R1UVb&quot;]/table[1]/tbody[1]/tr[4]/td[@class=&quot;x_no-padding-top-bottom-mobile&quot;]/table[@class=&quot;x_container&quot;]/tbody[1]/tr[1]/td[@class=&quot;x_container-padding&quot;]/table[@class=&quot;x_columns-container&quot;]/tbody[1]/tr[1]/td[@class=&quot;x_force-col&quot;]/table[@class=&quot;x_col-3&quot;]/tbody[1]/tr[1]/td[1]/div[2]/strong[1]</value>
      <webElementGuid>0c794c05-3880-4ca5-96a4-ac87fa3f96df</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ReadingPaneContainerId']/div/div/div/div/div/div[2]/div/div/div/div/div/div[3]/div/div/div/div[2]/table/tbody/tr[4]/td/table/tbody/tr/td/table/tbody/tr/td/table/tbody/tr/td/div[2]/strong</value>
      <webElementGuid>6150505b-3da3-48bb-9546-0d870a63f2fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hola, sjagtap'])[1]/following::strong[1]</value>
      <webElementGuid>013a9222-76d4-47aa-a247-a533891d2e23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Este es un procedimiento 100% seguro.'])[1]/preceding::strong[1]</value>
      <webElementGuid>71e93a71-e747-4093-8bc1-4dbe351a0150</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reply'])[2]/preceding::strong[2]</value>
      <webElementGuid>bb2f0a99-e31d-4e5d-8a49-0c1e8fefa5a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='559036']/parent::*</value>
      <webElementGuid>84260363-51e0-400d-8448-0e7828dfd2e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/strong</value>
      <webElementGuid>cfc9dfcd-7762-4d9b-86a2-6d0c0deef7e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//strong[(text() = '559036' or . = '559036')]</value>
      <webElementGuid>7d743e78-b8f5-4062-b199-e781ce914fe6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
