<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Hombre</name>
   <tag></tag>
   <elementGuidId>bd82702e-ce99-4bd2-800e-63c801656f00</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/header/div[3]/div[3]/div/nav/div/div/div/div/div/ul/li/ul/li[2]/a/div/div/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>8bd32f98-4035-4b87-acfd-a63c60e61a75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Hombre</value>
      <webElementGuid>ba83bcf0-c1c9-4daa-86b4-f3ba39ac14dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/header[1]/div[@class=&quot;o-header&quot;]/div[@class=&quot;o-container__fluid container-fluid wrap-megamenu d-none d-lg-block&quot;]/div[@class=&quot;o-container container p-0&quot;]/nav[@class=&quot;m-megamenu&quot;]/div[@class=&quot;o-row row align-items-center&quot;]/div[@class=&quot;o-col col-lg-10 col-xl-9 pr-0&quot;]/div[@class=&quot;o-row row&quot;]/div[@class=&quot;o-col col-lg-auto col-6 order-lg-1 text-center&quot;]/div[@class=&quot;o-navDesktop&quot;]/ul[@class=&quot;m-navDesktop__menuList&quot;]/li[@class=&quot;m-navDesktop__section pt-2 pb-2 mr-xl-5&quot;]/ul[@class=&quot;dropdown-menu m-megamenu__dropdown m-megamenu_dropdown_open&quot;]/li[@class=&quot;m-megamenu__category&quot;]/a[@class=&quot;a-dekstop__categoryLink&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-10&quot;]/span[1]</value>
      <webElementGuid>bb985131-53e0-4f01-9f56-319a6c88854b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/header/div[3]/div[3]/div/nav/div/div/div/div/div/ul/li/ul/li[2]/a/div/div/span</value>
      <webElementGuid>7cea92b5-eb7e-4ea4-bed0-a24197faae32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ver todas las secciones'])[1]/following::span[1]</value>
      <webElementGuid>7ec93c85-7c1a-404b-a55c-42934cb43470</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lentes'])[1]/following::span[1]</value>
      <webElementGuid>94697f56-8d49-46b3-af35-b99c44f67d9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hombre'])[2]/preceding::span[1]</value>
      <webElementGuid>05e405b2-2505-4a69-ac5f-f5ab2d1ba6e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ropa'])[2]/preceding::span[2]</value>
      <webElementGuid>7e0cc883-b0f9-4777-a0d8-14a74fa5a313</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Hombre']/parent::*</value>
      <webElementGuid>846f6543-61a3-4ad5-b064-f695e907162e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/a/div/div/span</value>
      <webElementGuid>653f1361-4d69-4371-b80a-3d1083eab68b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Hombre' or . = 'Hombre')]</value>
      <webElementGuid>2dc00460-4b0f-4ca4-bc33-7d1caf58a603</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
