<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Agregar a mi bolsa</name>
   <tag></tag>
   <elementGuidId>398c8367-81e7-4960-9959-82f3a5ea0e1d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#opc_pdp_addCartButton</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>42175ded-6a24-46e3-9b3f-f78810ef7388</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-btn a-btn--tertiary mb-3 </value>
      <webElementGuid>56c33ce6-da0a-423d-9c5b-5564e64c2721</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>opc_pdp_addCartButton</value>
      <webElementGuid>78869b87-f0d7-4508-8dd0-ff4ed98eddbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Agregar a mi bolsa</value>
      <webElementGuid>ffdd0ce5-98b5-40f5-9dee-6aeab0e1bbe5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;opc_pdp_addCartButton&quot;)</value>
      <webElementGuid>5fdf7ef4-6ba3-4311-865d-ce3e4b0cadf2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='opc_pdp_addCartButton']</value>
      <webElementGuid>42c3e7d5-9561-4559-a74c-174685c598eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/section/div/aside/div/div/aside/div[2]/div/div/button</value>
      <webElementGuid>742ecddd-abe9-47df-bc9b-28f9a7939719</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Recoge entre el 31 de enero y el 07 de febrero'])[1]/following::button[1]</value>
      <webElementGuid>6630e34b-f5e5-4d93-a08e-3a7a7a0a36fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cambiar dirección'])[1]/following::button[1]</value>
      <webElementGuid>6dde8d55-5f35-4b32-8bd7-fb709f34ed49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Guardar en Wishlist'])[1]/preceding::button[2]</value>
      <webElementGuid>7829b033-b8b7-4b7b-9cb7-f8b8e770429b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='John Leopard'])[1]/preceding::button[3]</value>
      <webElementGuid>2e78b559-ec04-4f02-a40d-3b03ab93ab86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/button</value>
      <webElementGuid>a3ce0af0-3ed3-4446-a103-d4a506e57d49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'opc_pdp_addCartButton' and (text() = 'Agregar a mi bolsa' or . = 'Agregar a mi bolsa')]</value>
      <webElementGuid>61d7c21f-9876-4457-833e-96b1340e8fdb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
