<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_G</name>
   <tag></tag>
   <elementGuidId>4361894f-5ff7-4444-ae95-163e91dc3742</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>202d37e2-55af-4c03-86fd-d41ff669af26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-btn a-btn--actionpdp</value>
      <webElementGuid>e98529e6-66d9-4310-a1bf-82829aa6cb1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-skuid</name>
      <type>Main</type>
      <value>1114530618</value>
      <webElementGuid>a205a094-e914-4815-898e-cada27f98cfa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> G </value>
      <webElementGuid>6aae12ac-1a93-49f9-8fbc-55fe75a53bed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;size-list-container&quot;)/li[3]/button[@class=&quot;a-btn a-btn--actionpdp&quot;]</value>
      <webElementGuid>2497dbaa-cc46-4249-b5c2-88d01cb05ecb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='size-list-container']/li[3]/button</value>
      <webElementGuid>fef18c3d-7b34-42d9-a449-299efca56c5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Chamarra Para Hombre Puffed Parka Con Peluche'])[1]/preceding::button[3]</value>
      <webElementGuid>5ad32969-920f-434a-bcde-83f61803458c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='G']/parent::*</value>
      <webElementGuid>077bf996-be91-4103-9648-1d901843bba0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/button</value>
      <webElementGuid>e6a07918-19ff-4159-8298-35864f8e6e2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = ' G ' or . = ' G ')]</value>
      <webElementGuid>2f55d6d4-995b-4336-8f4f-d960a3190b0b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
