<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Comprar</name>
   <tag></tag>
   <elementGuidId>0b409e6c-77cc-49a7-8b53-caf4c5c24395</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@id='opc_pdp_buyNowButton'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>32a31701-8f54-46fd-94ca-1c9d0556c566</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>GeoComprarBtn a-btn a-btn--primary</value>
      <webElementGuid>877845be-8cd5-4d75-aa04-6e8491cc3c41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>opc_pdp_buyNowButton</value>
      <webElementGuid>d3d6676a-315c-4806-9fcc-17e0ee3ab99d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Comprar</value>
      <webElementGuid>35ce80cd-4a73-4812-95ee-694ee5819686</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;min-vh-100&quot;]/section[@class=&quot;o-product__detail&quot;]/div[@class=&quot;container o-product__mainContainer&quot;]/aside[@class=&quot;o-product__purchase p-0 pt-lg-3 pr-lg-3 pl-lg-3 GeoTopMargin&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-12 col-lg-12&quot;]/aside[@class=&quot;o-product__productInfo pb-lg-4&quot;]/div[1]/div[@class=&quot;row o-product__productEdd&quot;]/div[@class=&quot;col&quot;]/div[3]/div[@class=&quot;GeoLocationCard&quot;]/div[@class=&quot;d-flex&quot;]/div[@class=&quot;GeoCardWidth bt-disabled-secondary&quot;]/button[@id=&quot;opc_pdp_buyNowButton&quot;]</value>
      <webElementGuid>f580a549-0404-425c-b085-6ce54e8e6333</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@id='opc_pdp_buyNowButton'])[2]</value>
      <webElementGuid>2c3f7ade-8cb9-467c-b146-d3a51eda5d0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/section/div/aside/div/div/aside/div/div/div/div[3]/div[2]/div/div/button</value>
      <webElementGuid>2694a40b-f2f9-4b2f-9894-7bf1dad411a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[2]/following::button[1]</value>
      <webElementGuid>cfa45011-ae2f-4daa-ae79-f9344f893063</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Recibe a domicilio'])[1]/preceding::button[1]</value>
      <webElementGuid>51790c03-db3f-46be-8e10-86bcdba6b849</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cambiar dirección'])[1]/preceding::button[1]</value>
      <webElementGuid>5e087fa6-7e65-4d16-b229-a9bd17add8a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/div/button</value>
      <webElementGuid>e7c2380d-d2d9-42ab-be02-c7de19ac7256</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'opc_pdp_buyNowButton' and (text() = 'Comprar' or . = 'Comprar')]</value>
      <webElementGuid>7c92e1dc-731c-4079-b1e3-83cdd77178cb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
