<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Comprar ahora</name>
   <tag></tag>
   <elementGuidId>8ba2caba-85c1-4a51-8a71-420975eed90c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#sticky__button-addToExpressCart</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='sticky__button-addToExpressCart']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4a06a097-bcd9-4a5f-a6a8-4267cefe59ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-btn a-btn--primary</value>
      <webElementGuid>972b8934-eb8c-4b5b-a616-dba884e772c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>sticky__button-addToExpressCart</value>
      <webElementGuid>206a05b0-62f5-468f-9576-187cb4d2be8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Comprar ahora</value>
      <webElementGuid>8623ab7e-1e5b-4395-987b-1e33c816f8b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sticky__button-addToExpressCart&quot;)</value>
      <webElementGuid>4458078e-cfc2-495d-b7f1-d3acda5f97e9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='sticky__button-addToExpressCart']</value>
      <webElementGuid>1b37b150-1a46-4276-afd0-c27cbb424ae2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[4]/div/div/div/div[3]/div/div/div[3]/div[2]/button</value>
      <webElementGuid>c05a2c7d-7da9-498b-a102-df8ccc3a1c62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Agregar a mi bolsa'])[1]/following::button[1]</value>
      <webElementGuid>9046a11c-a776-4d36-a6b6-41421d19f438</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='+'])[1]/following::button[2]</value>
      <webElementGuid>08b29831-7188-4d8f-b345-63cdc3f12b34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[1]/preceding::button[1]</value>
      <webElementGuid>da469080-048a-4ac6-a0ae-d1a9a90f7895</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hombre'])[1]/preceding::button[1]</value>
      <webElementGuid>2776a8e5-49e6-4b04-ab7d-d54059693949</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Comprar ahora']/parent::*</value>
      <webElementGuid>76f53d70-4203-4355-88ab-2d254f548b4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button</value>
      <webElementGuid>2e0f9ece-92d0-4ff3-b884-5b1d1ec561f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'sticky__button-addToExpressCart' and (text() = 'Comprar ahora' or . = 'Comprar ahora')]</value>
      <webElementGuid>56f570a8-1ecb-4fa6-911f-9c69c4260965</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
