<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Joyera</name>
   <tag></tag>
   <elementGuidId>1ea63726-ef5f-4d06-972e-e1e7b40d1594</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div/div/div/div[4]/aside/div/div/div/ul/li[5]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>9bc1ba70-1feb-40c6-b194-922342daa88e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-category__listElement 
                                </value>
      <webElementGuid>ffd072ab-ec66-4b9d-b13c-828c130907ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/tienda/joyer%C3%ADa/catst44696801</value>
      <webElementGuid>b311cecd-6888-4539-96ba-19ab5b926ba7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Joyería</value>
      <webElementGuid>2828380b-6a8d-4220-8380-7380d1614f62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;min-vh-100&quot;]/div[1]/div[@class=&quot;container-fluid o-main-container p-0 o-blp-secondaryContainer&quot;]/div[@class=&quot;container o-container__secondary&quot;]/div[@class=&quot;row mt-lg-3 m-row-bootstrap&quot;]/aside[@class=&quot;col-lg-3 pr-lg-4 m-aside__content&quot;]/div[@class=&quot;col-12 mr-lg-4 order-2 order-lg-1 mb-3 px-0 o-column__aside&quot;]/div[1]/div[@class=&quot;m-leftMenu-wrapper plp-filter-options active&quot;]/ul[@class=&quot;nav-sub-options-leftMenu pl-40&quot;]/li[@class=&quot;nav-sub-link-leftMenu&quot;]/a[@class=&quot;a-category__listElement&quot;]</value>
      <webElementGuid>ef1f9188-34be-4cfb-bc3b-03ed8ef24653</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div/div/div[4]/aside/div/div/div/ul/li[5]/a</value>
      <webElementGuid>d0b96a30-a9b2-42ad-a276-456aed774863</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Joyería')]</value>
      <webElementGuid>c942350a-0e8b-4720-a35e-1fd2fad4b941</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cuidado Personal'])[1]/following::a[1]</value>
      <webElementGuid>9e5b1caa-4763-47e9-8a22-0cacc5eb24f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Accesorios de Hombre'])[1]/following::a[2]</value>
      <webElementGuid>f1c1b0a9-4353-45f0-adab-0e292744f536</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='HOMBRE'])[2]/preceding::a[1]</value>
      <webElementGuid>325f5650-bfe4-4789-8385-19d9f503c42d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MOCHILAS'])[2]/preceding::a[1]</value>
      <webElementGuid>9ea9d6f8-bca1-44f9-8846-0f84bf012688</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Joyería']/parent::*</value>
      <webElementGuid>319918d6-cb26-4660-aa5b-f062420ba1b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/tienda/joyer%C3%ADa/catst44696801')])[2]</value>
      <webElementGuid>6f915869-661f-4b80-8be2-cbba0cd36274</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//aside/div/div/div/ul/li[5]/a</value>
      <webElementGuid>3bc9c9a0-b622-4e62-9333-4f838926f888</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/tienda/joyer%C3%ADa/catst44696801' and (text() = 'Joyería' or . = 'Joyería')]</value>
      <webElementGuid>969accd6-1148-43e5-a04e-078d8c59b675</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
