<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Ropa</name>
   <tag></tag>
   <elementGuidId>3e72c629-f93c-4b9e-b773-25e429edf26d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div/div/div/div[4]/aside/div/div/div/ul/li/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>2257d492-2763-49c0-9ba3-d85c4bd538dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-category__listElement 
                                </value>
      <webElementGuid>638f2865-d51b-4e5b-ae5f-9c2cdda6bc75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/tienda/ropa/cat610037</value>
      <webElementGuid>62e6b4ca-3574-4c3c-ae53-31e14ff8d0b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ropa</value>
      <webElementGuid>79ccfa9b-1784-4f2a-82ee-ff0c63ff42d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;min-vh-100&quot;]/div[1]/div[@class=&quot;container-fluid o-main-container p-0 o-blp-secondaryContainer&quot;]/div[@class=&quot;container o-container__secondary&quot;]/div[@class=&quot;row mt-lg-3 m-row-bootstrap&quot;]/aside[@class=&quot;col-lg-3 pr-lg-4 m-aside__content&quot;]/div[@class=&quot;col-12 mr-lg-4 order-2 order-lg-1 mb-3 px-0 o-column__aside&quot;]/div[1]/div[@class=&quot;m-leftMenu-wrapper plp-filter-options active&quot;]/ul[@class=&quot;nav-sub-options-leftMenu pl-40&quot;]/li[@class=&quot;nav-sub-link-leftMenu&quot;]/a[@class=&quot;a-category__listElement&quot;]</value>
      <webElementGuid>decab123-3543-4eb2-b035-6c83c5d1ee89</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div/div/div[4]/aside/div/div/div/ul/li/a</value>
      <webElementGuid>8cbe0eae-be5d-4f83-a0ca-f691ab397087</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Ropa')]</value>
      <webElementGuid>9b92d667-7865-43af-b973-5ea4348177e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hombre'])[6]/following::a[1]</value>
      <webElementGuid>e5f7d8e3-3496-4424-8783-b601513cc6fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hombre'])[5]/following::a[1]</value>
      <webElementGuid>011fb26e-58a7-4e03-84a0-a716d34cefa7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Zapatos'])[1]/preceding::a[1]</value>
      <webElementGuid>38dac938-44d2-4fdc-a147-1fec1e362f6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Accesorios de Hombre'])[1]/preceding::a[2]</value>
      <webElementGuid>6b89d212-1806-4629-b771-36eccf2e6f9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Ropa']/parent::*</value>
      <webElementGuid>a8d264e6-1dbf-424f-91d8-229f2bf9c624</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/tienda/ropa/cat610037')]</value>
      <webElementGuid>5a7c18b4-8761-4249-a224-2502f974bc6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//aside/div/div/div/ul/li/a</value>
      <webElementGuid>59f99928-12ea-4ede-b70f-7a17d8d15713</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/tienda/ropa/cat610037' and (text() = 'Ropa' or . = 'Ropa')]</value>
      <webElementGuid>2d83340c-5cd6-4559-a202-f2340827b48c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Ropa')])[10]</value>
      <webElementGuid>84a4b4ef-9c7f-4aba-930e-f280563cbbda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hombre'])[10]/following::a[1]</value>
      <webElementGuid>dfc32fcc-784f-4eba-9151-058f78ca167c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hombre'])[9]/following::a[1]</value>
      <webElementGuid>683098ec-8495-488f-9bee-5dc40b4cddea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Zapatos'])[11]/preceding::a[1]</value>
      <webElementGuid>0f45b42f-8981-49f0-b880-652e2e736d3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Accesorios de Hombre'])[2]/preceding::a[2]</value>
      <webElementGuid>bc09e2ce-7dc6-4859-a4ee-4f08f7c2f25c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
