<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Comprar</name>
   <tag></tag>
   <elementGuidId>0871ba83-854c-484d-b7e2-f80db5d36fb5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@id='opc_pdp_buyNowButton'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9c0a0b12-13b0-44dc-b48f-c61e08d4d112</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>GeoComprarBtn a-btn a-btn--primary</value>
      <webElementGuid>213a14c5-cd54-4906-ab39-0e13cd21ea2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>opc_pdp_buyNowButton</value>
      <webElementGuid>b0fddc37-6ac4-4ee6-a03c-cd8e1e09be35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Comprar</value>
      <webElementGuid>53e9c449-d524-4f54-ba3d-c109c72a5e54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;min-vh-100&quot;]/section[@class=&quot;o-product__detail&quot;]/div[@class=&quot;container o-product__mainContainer&quot;]/aside[@class=&quot;o-product__purchase p-0 pt-lg-3 pr-lg-3 pl-lg-3 GeoTopMargin&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-12 col-lg-12&quot;]/aside[@class=&quot;o-product__productInfo pb-lg-4&quot;]/div[1]/div[@class=&quot;row o-product__productEdd&quot;]/div[@class=&quot;col&quot;]/div[3]/div[@class=&quot;GeoLocationCard&quot;]/div[@class=&quot;d-flex&quot;]/div[@class=&quot;GeoCardWidth bt-disabled-secondary&quot;]/button[@id=&quot;opc_pdp_buyNowButton&quot;]</value>
      <webElementGuid>40b63223-41ac-40f3-a744-a981d54fe5d7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@id='opc_pdp_buyNowButton'])[2]</value>
      <webElementGuid>b4930f0c-b972-45d8-b27f-4ef86f2cb633</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/section/div/aside/div/div/aside/div/div/div/div[3]/div[2]/div/div/button</value>
      <webElementGuid>c5ae9a4b-c19c-436b-beda-7d19f8676e81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[2]/following::button[1]</value>
      <webElementGuid>7f771602-4f7c-47f0-8649-980162cf643e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Recibe a domicilio'])[1]/preceding::button[1]</value>
      <webElementGuid>f3c47edc-37e8-4237-b379-f7b8b48255cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cambiar dirección'])[1]/preceding::button[1]</value>
      <webElementGuid>b0be2c5a-c020-4f2e-ab77-a0904d10fcfb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/div/button</value>
      <webElementGuid>ba98d667-e238-4b54-aa45-d66576edf6a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'opc_pdp_buyNowButton' and (text() = 'Comprar' or . = 'Comprar')]</value>
      <webElementGuid>168d6a74-a5bd-4230-a9c3-01d2ce31aaec</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
