<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Inicia sesin_elektra-elektra-components_7932e9</name>
   <tag></tag>
   <elementGuidId>b38e03d2-0167-4213-8054-58e9ec840c0c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.elektra-elektra-components-0-x-chevron.vtex-render-runtime-8-x-lazyload.ls-is-cached.lazyloaded</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@alt='icn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>96a30e33-74a8-4e39-91d9-fdb0e549156c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>icn</value>
      <webElementGuid>97c2ef76-963f-4a6a-b08d-bf5a672fd0ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>elektra-elektra-components-0-x-chevron vtex-render-runtime-8-x-lazyload ls-is-cached lazyloaded</value>
      <webElementGuid>afde14d3-d45c-44f1-ba53-0fd6c376b0ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-src</name>
      <type>Main</type>
      <value>https://dh3yyy4wyj8lf.cloudfront.net/ekt-storefront/img-sites/components-io/Envios_table_content_Chevrone-down.svg</value>
      <webElementGuid>59450f5c-13fa-4a28-b33d-1ed916171c64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>dd71dda1-e500-4e0f-af6c-8c62c2b20a59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://dh3yyy4wyj8lf.cloudfront.net/ekt-storefront/img-sites/components-io/Envios_table_content_Chevrone-down.svg</value>
      <webElementGuid>65727413-7756-490d-b32f-79dd14cb7e88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;bg-base&quot;]/div[@class=&quot;render-container render-route-store-home&quot;]/div[@class=&quot;render-provider&quot;]/div[@class=&quot;vtex-store__template bg-base&quot;]/div[@class=&quot;flex flex-column min-vh-100 w-100&quot;]/div[@class=&quot;vtex-sticky-layout-0-x-wrapper vtex-sticky-layout-0-x-wrapper--sticky-header-1&quot;]/div[@class=&quot;vtex-sticky-layout-0-x-container vtex-sticky-layout-0-x-container--sticky-header-1 z-999 relative left-0 right-0&quot;]/div[@class=&quot;vtex-flex-layout-0-x-flexRow vtex-flex-layout-0-x-flexRow--menu-link&quot;]/div[@class=&quot;flex mt0 mb0 pt0 pb0    justify-center vtex-flex-layout-0-x-flexRowContent vtex-flex-layout-0-x-flexRowContent--menu-link items-stretch w-100&quot;]/div[@class=&quot;pr0     flex&quot;]/div[@class=&quot;elektra-elektra-components-0-x-containerUserPlaceholder&quot;]/div[@class=&quot;elektra-elektra-components-0-x-placeholderNoLogin&quot;]/img[@class=&quot;elektra-elektra-components-0-x-chevron vtex-render-runtime-8-x-lazyload ls-is-cached lazyloaded&quot;]</value>
      <webElementGuid>0aebf645-c780-4740-afc9-04341cb7bb7b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='icn']</value>
      <webElementGuid>30d80fe0-bd17-4d84-be1c-99dc1ef8bb24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/img[2]</value>
      <webElementGuid>4973944e-1db9-4bcd-b022-e87b0b7cab77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'icn' and @src = 'https://dh3yyy4wyj8lf.cloudfront.net/ekt-storefront/img-sites/components-io/Envios_table_content_Chevrone-down.svg']</value>
      <webElementGuid>7616d5f0-8bec-49d8-a9a1-570893a7e3f9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
