<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Inicia sesin_elektra-elektra-components_50b0a5</name>
   <tag></tag>
   <elementGuidId>690d6805-294a-421e-a23a-93f3c644d31d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@alt='icn']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.elektra-elektra-components-0-x-chevron.vtex-render-runtime-8-x-lazyload.lazyloaded</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>5e716cf5-603a-4666-81d3-9e9d28d3f826</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>icn</value>
      <webElementGuid>e951085b-4e05-44cd-b06e-1ef74774ef2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>elektra-elektra-components-0-x-chevron vtex-render-runtime-8-x-lazyload lazyloaded</value>
      <webElementGuid>0906c51b-4b0a-4202-96ee-2b6b3c684c50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-src</name>
      <type>Main</type>
      <value>https://dh3yyy4wyj8lf.cloudfront.net/ekt-storefront/img-sites/components-io/Envios_table_content_Chevrone-down.svg</value>
      <webElementGuid>683c2ce9-29d3-441b-a486-aebed0adbf80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>dc83c347-b553-4337-9f8e-6ff9bec69fab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://dh3yyy4wyj8lf.cloudfront.net/ekt-storefront/img-sites/components-io/Envios_table_content_Chevrone-down.svg</value>
      <webElementGuid>7ed0c7f9-325a-47a1-9406-924f997cfd9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;bg-base&quot;]/div[@class=&quot;render-container render-route-store-home&quot;]/div[@class=&quot;render-provider&quot;]/div[@class=&quot;vtex-store__template bg-base&quot;]/div[@class=&quot;flex flex-column min-vh-100 w-100&quot;]/div[@class=&quot;vtex-sticky-layout-0-x-wrapper vtex-sticky-layout-0-x-wrapper--sticky-header-1&quot;]/div[@class=&quot;vtex-sticky-layout-0-x-container vtex-sticky-layout-0-x-container--sticky-header-1 z-999 relative left-0 right-0&quot;]/div[@class=&quot;vtex-flex-layout-0-x-flexRow vtex-flex-layout-0-x-flexRow--menu-link&quot;]/div[@class=&quot;flex mt0 mb0 pt0 pb0    justify-center vtex-flex-layout-0-x-flexRowContent vtex-flex-layout-0-x-flexRowContent--menu-link items-stretch w-100&quot;]/div[@class=&quot;pr0     flex&quot;]/div[@class=&quot;elektra-elektra-components-0-x-containerUserPlaceholder&quot;]/div[@class=&quot;elektra-elektra-components-0-x-placeholderNoLogin&quot;]/img[@class=&quot;elektra-elektra-components-0-x-chevron vtex-render-runtime-8-x-lazyload lazyloaded&quot;]</value>
      <webElementGuid>33b070f1-04e6-4522-b592-563803f9e864</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='icn']</value>
      <webElementGuid>5641a476-8a6c-478e-9ae2-bd346468c905</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/img[2]</value>
      <webElementGuid>edc8af70-2663-40e7-b13d-b6bbaa0a595e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'icn' and @src = 'https://dh3yyy4wyj8lf.cloudfront.net/ekt-storefront/img-sites/components-io/Envios_table_content_Chevrone-down.svg']</value>
      <webElementGuid>d4284633-8fe6-4f72-998b-aae585a7c722</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
