<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Finalizar compra</name>
   <tag></tag>
   <elementGuidId>65701981-c640-41e1-8969-bf82ec2a74c8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#submitForOther</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='submitForOther']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5a761086-823c-4d20-9fce-9cb941317eac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-btn a-btn--primary</value>
      <webElementGuid>c174da27-9ab8-4676-a0e4-89568fadf442</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>submitForOther</value>
      <webElementGuid>8662abe9-1238-4380-9c80-549668a89504</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Finalizar compra</value>
      <webElementGuid>c2317bb2-00cd-4b59-82ad-25bb551bba85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;submitForOther&quot;)</value>
      <webElementGuid>84d9f86e-835f-403c-943a-140cbc642b8b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='submitForOther']</value>
      <webElementGuid>5c8c582c-ba28-4cd8-b182-b27ce4d9e7f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='opc_container']/div[6]/div[2]/div/div[3]/div[2]/button</value>
      <webElementGuid>5a45b5f6-9063-47e1-9a59-eccfd4c9416f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Términos, Condiciones y Aviso de Privacidad'])[1]/following::button[1]</value>
      <webElementGuid>f22b7038-0d3e-4208-83af-9fa5dc801527</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$419.30'])[2]/following::button[1]</value>
      <webElementGuid>4c1b8344-ca14-44ee-beb8-af717f326a3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cambios, devoluciones y cancelaciones'])[1]/preceding::button[1]</value>
      <webElementGuid>e4ec1016-7255-435f-97bc-1e98644f9673</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Preguntas frecuentes'])[1]/preceding::button[1]</value>
      <webElementGuid>4232c106-e657-4811-b03b-3a03c83b8451</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Finalizar compra']/parent::*</value>
      <webElementGuid>31c98b5f-1fa6-4dfd-ad26-8352868b233f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button</value>
      <webElementGuid>cfe2a64e-1d31-471b-9066-4f5e5e57c4e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'submitForOther' and (text() = 'Finalizar compra' or . = 'Finalizar compra')]</value>
      <webElementGuid>61c4ca50-c18f-40c4-8854-1e0ed94e63b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$909.30'])[2]/following::button[1]</value>
      <webElementGuid>3d1cca01-d26b-470a-8229-902db427a397</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='opc_container']/div[6]/div[2]/div/div[4]/div[2]/button</value>
      <webElementGuid>11b6aac9-6435-4518-8fac-f1a99f3e3b4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$1,889.00'])[2]/following::button[1]</value>
      <webElementGuid>3194fef5-a9a4-4456-bde9-061bf83364ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/button</value>
      <webElementGuid>d32ca0e2-2c78-4f4f-bd75-3e7913700d3a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
