<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Confirma tu compra_a-checkbox__input _443bf0</name>
   <tag></tag>
   <elementGuidId>685d5aca-d6c4-4092-993c-fd8e4a5832c0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.a-checkbox__input.mdc-checkbox__native-control</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>40b24bd6-7a61-40fc-9beb-98be59c9f4d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-checkbox__input mdc-checkbox__native-control</value>
      <webElementGuid>2efa441a-28e3-4ae1-b8a9-134c4b58f4f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>a2d253b0-3526-43db-8905-f0035b86c33f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>7418c39a-d8b3-4449-908d-0c0ba0dc1a2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;opc_setDefautPayment-checkbox&quot;)/div[@class=&quot;a-checkout-defaultPayment m-checkbox__button mdc-form-field&quot;]/div[@class=&quot;m-checkbox mdc-checkbox mdc-checkbox--upgraded mdc-ripple-upgraded mdc-ripple-upgraded--unbounded undefined&quot;]/input[@class=&quot;a-checkbox__input mdc-checkbox__native-control&quot;]</value>
      <webElementGuid>aba58b88-56a4-46fa-8c54-4fd56e626827</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='']</value>
      <webElementGuid>e85ca924-9f9a-4ddb-9211-cf49e3543abf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='opc_setDefautPayment-checkbox']/div/div/input</value>
      <webElementGuid>804cc2e3-df44-4973-a973-59e49b93ff7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>9b908d18-7f96-4bbc-89aa-c1b6f778b512</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox']</value>
      <webElementGuid>8d29d950-10f7-49b0-b612-2cde17fbb77a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
