<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Cambiar</name>
   <tag></tag>
   <elementGuidId>dc3a82c0-c42f-4353-9fce-05c97ab16195</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>label.text-shutdown-card.cambiarLabelTxt.text-size-card</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='opc_section-PayMethod']/div/div[2]/button/div/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>479b94a3-2f54-43f2-8727-84072f3f517c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-shutdown-card cambiarLabelTxt text-size-card</value>
      <webElementGuid>f230ee53-be28-475e-94b1-0cb46c7c5451</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cambiar</value>
      <webElementGuid>b9aeed3d-1874-4060-b868-8879c5567a8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;opc_section-PayMethod&quot;)/div[@class=&quot;d-flex flex-row align-items-start justify-content-start pt-1 pl-2 pr-1&quot;]/div[@class=&quot;w-100&quot;]/button[@class=&quot;a-btn a-btn--onePageCheckout--deliveryAddress d-inline&quot;]/div[@class=&quot;a-box__accordionIcon float-right&quot;]/label[@class=&quot;text-shutdown-card cambiarLabelTxt text-size-card&quot;]</value>
      <webElementGuid>beaa4de4-337b-4aae-855d-0f7923d157b5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='opc_section-PayMethod']/div/div[2]/button/div/label</value>
      <webElementGuid>81941f4b-ef30-4b9d-8a6d-7d02515abfbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*9488'])[1]/following::label[1]</value>
      <webElementGuid>74472167-4d10-45a3-90a9-c2ce4ae72926</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MM/AA'])[1]/preceding::label[1]</value>
      <webElementGuid>f40682b0-556e-430e-b054-9e20c112b82b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CVV'])[1]/preceding::label[2]</value>
      <webElementGuid>c443f60e-41b6-4e88-a360-7979c5767e7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button/div/label</value>
      <webElementGuid>e03dc72e-095e-41ed-a52d-2123fbbb11c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Cambiar' or . = 'Cambiar')]</value>
      <webElementGuid>e9597a97-556b-4240-b79c-5a219398d35b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
