<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Sudaderas_card-img-top</name>
   <tag></tag>
   <elementGuidId>7ce68391-dbda-4ec3-a235-835f2f3fcdde</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/main/div/div/div/div[2]/div/div[2]/section/div/div[4]/div/figure/a/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>479e427f-3dc5-4446-a74a-2b7633aa2b9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>a39ac016-1ca7-4709-a399-6c3d6098b449</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://assets.liverpool.com.mx/assets/images/categorias/el/cat850065.jpg</value>
      <webElementGuid>d851a7c9-501f-45ed-8205-4f74ea01a5c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>card-img-top</value>
      <webElementGuid>94169c36-72bf-4771-9385-2d256e362992</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;min-vh-100&quot;]/main[1]/div[@class=&quot;container-fluid o-main-container p-0 o-clp-secondaryContainer&quot;]/div[@class=&quot;container o-container__secondary&quot;]/div[1]/div[@class=&quot;row mt-lg-3 m-row-bootstrap leftMenu-clpMobile&quot;]/div[@class=&quot;col-lg-9 m-column_mainContent clp_headband&quot;]/div[@class=&quot;o-clp-mainContent&quot;]/section[@class=&quot;clp_body&quot;]/div[@class=&quot;o-cards-row o-clp-cards-row mt-lg-4&quot;]/div[@class=&quot;o-clp-cards-row_container&quot;]/div[1]/figure[@class=&quot;m-figureCard__figure card  m-card&quot;]/a[1]/div[@class=&quot;lazyload-wrapper&quot;]/img[@class=&quot;card-img-top&quot;]</value>
      <webElementGuid>ec35e5f4-e11c-48c1-ae84-276fcba7d484</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/main/div/div/div/div[2]/div/div[2]/section/div/div[4]/div/figure/a/div/img</value>
      <webElementGuid>66fb1a74-58f3-4272-abe6-88e4490727a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://assets.liverpool.com.mx/assets/images/categorias/el/cat850065.jpg')]</value>
      <webElementGuid>8f871225-e40e-4339-9fd2-cc453fd221fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/figure/a/div/img</value>
      <webElementGuid>6fefa0d7-682d-4287-8123-7e82197742f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://assets.liverpool.com.mx/assets/images/categorias/el/cat850065.jpg']</value>
      <webElementGuid>803ffb16-aa5c-4c91-86f7-03aed9873fd5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
